package au.com.project.sample.services.admin.service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-04T22:39:27.834+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/Service/v1", name = "Service")
@XmlSeeAlso({au.com.project.sample.common.message.response.v1.ObjectFactory.class, au.com.project.sample.services.admin.service.serviceresponse.v1.ObjectFactory.class, au.com.project.sample.common.message.request.v1.ObjectFactory.class, au.com.project.sample.common.message.responsemessage.v1.ObjectFactory.class, au.com.project.sample.common.message.header.v1.ObjectFactory.class, au.com.project.sample.common.message.technicalexception.v1.ObjectFactory.class, au.com.project.sample.common.message.fault.v1.ObjectFactory.class, au.com.project.sample.services.admin.service.servicerequest.v1.ObjectFactory.class, au.com.project.sample.common.message.notifications.v1.ObjectFactory.class, au.com.project.sample.common.message.businessexception.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Service {

    @WebResult(name = "serviceResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/Service/ServiceResponse/v1", partName = "response")
    @WebMethod(operationName = "Service", action = "http://www.sample.project.com.au/services/admin/Service/v1")
    public au.com.project.sample.services.admin.service.serviceresponse.v1.ServiceResponse service(
        @WebParam(partName = "request", name = "serviceRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/Service/ServiceRequest/v1")
        au.com.project.sample.services.admin.service.servicerequest.v1.ServiceRequest request
    ) throws au.com.project.sample.common.message.faultmessage.v1.BusinessFault, au.com.project.sample.common.message.faultmessage.v1.TechnicalFault;
}
