package au.com.project.sample.services.admin.service.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-04T22:39:27.926+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "Service", 
                  wsdlLocation = "Service.wsdl",
                  targetNamespace = "http://www.sample.project.com.au/services/admin/Service/v1") 
public class Service_Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sample.project.com.au/services/admin/Service/v1", "Service");
    public final static QName ServiceSOAP = new QName("http://www.sample.project.com.au/services/admin/Service/v1", "ServiceSOAP");
    static {
        URL url = Service_Service.class.getResource("Service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Service_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "Service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public Service_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServiceSOAP")
    public Service getServiceSOAP() {
        return super.getPort(ServiceSOAP, Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServiceSOAP")
    public Service getServiceSOAP(WebServiceFeature... features) {
        return super.getPort(ServiceSOAP, Service.class, features);
    }

}
