package au.com.project.sample.registration.services.getcountry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-05T13:42:42.246+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/registration/services/GetCountry/v1", name = "GetCountry")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetCountry {

    @WebResult(name = "getCountryResponse", targetNamespace = "http://www.sample.project.com.au/registration/services/GetCountry/v1", partName = "response")
    @WebMethod(operationName = "GetCountry", action = "http://www.sample.project.com.au/registration/services/GetCountry/v1")
    public au.com.project.sample.registration.services.getcountry.GetCountryResponse getCountry(
        @WebParam(partName = "request", name = "getCountryRequest", targetNamespace = "http://www.sample.project.com.au/registration/services/GetCountry/v1")
        au.com.project.sample.registration.services.getcountry.GetCountryRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
