package au.com.project.sample.services.admin.deletecategory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:20:50.481+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteCategory/v1", name = "DeleteCategory")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteCategory {

    @WebResult(name = "deleteCategoryResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteCategory/DeleteCategoryResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteCategory", action = "http://www.sample.project.com.au/services/admin/DeleteCategory/v1")
    public au.com.project.sample.services.admin.deletecategory.DeleteCategoryResponse deleteCategory(
        @WebParam(partName = "request", name = "deleteCategoryRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteCategory/DeleteCategoryRequest/v1")
        au.com.project.sample.services.admin.deletecategory.DeleteCategoryRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
