package au.com.project.sample.services.admin.updaterole;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:22:13.593+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateRole/v1", name = "UpdateRole")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateRole {

    @WebResult(name = "updateRoleResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateRole/UpdateRoleResponse/v1", partName = "response")
    @WebMethod(operationName = "UpdateRole", action = "http://www.sample.project.com.au/services/admin/UpdateRole/v1")
    public au.com.project.sample.services.admin.updaterole.UpdateRoleResponse updateRole(
        @WebParam(partName = "request", name = "updateRoleRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateRole/UpdateRoleRequest/v1")
        au.com.project.sample.services.admin.updaterole.UpdateRoleRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
