package au.com.project.sample.services.admin.createcurrency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-19T09:50:27.837+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/CreateCurrency/v1", name = "CreateCurrency")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateCurrency {

    @WebResult(name = "createCurrencyResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateCurrency/CreateCurrencyResponse/v1", partName = "response")
    @WebMethod(operationName = "CreateCurrency", action = "http://www.sample.project.com.au/services/admin/CreateCurrency/v1")
    public au.com.project.sample.services.admin.createcurrency.CreateCurrencyResponse createCurrency(
        @WebParam(partName = "request", name = "createCurrencyRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateCurrency/CreateCurrencyRequest/v1")
        au.com.project.sample.services.admin.createcurrency.CreateCurrencyRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
