package au.com.project.sample.services.admin.deletecurrency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:02.417+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteCurrency/v1", name = "DeleteCurrency")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteCurrency {

    @WebResult(name = "deleteCurrencyResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteCurrency/DeleteCurrencyResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteCurrency", action = "http://www.sample.project.com.au/services/admin/DeleteCurrency/v1")
    public au.com.project.sample.services.admin.deletecurrency.DeleteCurrencyResponse deleteCurrency(
        @WebParam(partName = "request", name = "deleteCurrencyRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteCurrency/DeleteCurrencyRequest/v1")
        au.com.project.sample.services.admin.deletecurrency.DeleteCurrencyRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
