package au.com.project.sample.registration.services.setstate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-05T13:43:17.176+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/registration/services/SetState/v1", name = "SetState")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SetState {

    @WebResult(name = "setStateResponse", targetNamespace = "http://www.sample.project.com.au/registration/services/SetState/SetStateResponse/v1", partName = "response")
    @WebMethod(operationName = "SetState", action = "http://www.sample.project.com.au/registration/services/SetState/v1")
    public au.com.project.sample.registration.services.setstate.SetStateResponse setState(
        @WebParam(partName = "request", name = "setStateRequest", targetNamespace = "http://www.sample.project.com.au/registration/services/SetState/SetStateRequest/v1")
        au.com.project.sample.registration.services.setstate.SetStateRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
