package au.com.project.sample.services.admin.createcountry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:20:26.058+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/CreateCountry/v1", name = "CreateCountry")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateCountry {

    @WebResult(name = "createCountryResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateCountry/CreateCountryResponse/v1", partName = "response")
    @WebMethod(operationName = "CreateCountry", action = "http://www.sample.project.com.au/services/admin/CreateCountry/v1")
    public au.com.project.sample.services.admin.createcountry.CreateCountryResponse createCountry(
        @WebParam(partName = "request", name = "createCountryRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateCountry/CreateCountryRequest/v1")
        au.com.project.sample.services.admin.createcountry.CreateCountryRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
