package au.com.project.sample.services.account.deleteemploymentsummary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-22T11:38:41.345+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/account/DeleteEmploymentSummary/v1", name = "DeleteEmploymentSummary")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteEmploymentSummary {

    @WebResult(name = "deleteEmploymentSummaryResponse", targetNamespace = "http://www.sample.project.com.au/services/account/DeleteEmploymentSummary/DeleteEmploymentSummaryResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteEmploymentSummary", action = "http://www.sample.project.com.au/services/account/DeleteEmploymentSummary/v1")
    public au.com.project.sample.services.account.deleteemploymentsummary.DeleteEmploymentSummaryResponse deleteEmploymentSummary(
        @WebParam(partName = "request", name = "deleteEmploymentSummaryRequest", targetNamespace = "http://www.sample.project.com.au/services/account/DeleteEmploymentSummary/DeleteEmploymentSummaryRequest/v1")
        au.com.project.sample.services.account.deleteemploymentsummary.DeleteEmploymentSummaryRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
