package au.com.project.sample.services.admin.deleterole;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2 2013-02-24T02:21:10.321+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteRole/v1", name = "DeleteRole")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteRole {

	@WebResult(name = "deleteRoleResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteRole/DeleteRoleResponse/v1", partName = "response")
	@WebMethod(operationName = "DeleteRole", action = "http://www.sample.project.com.au/services/admin/DeleteRole/v1")
	public au.com.project.sample.services.admin.deleterole.DeleteRoleResponse deleteRole(
			@WebParam(partName = "request", name = "deleteRoleRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteRole/DeleteRoleRequest/v1") au.com.project.sample.services.admin.deleterole.DeleteRoleRequest request)
			throws au.com.project.sample.common.message.TechnicalFault,
			au.com.project.sample.common.message.BusinessFault;
}
