package au.com.project.sample.services.admin.updatecurrency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:22:05.786+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateCurrency/v1", name = "UpdateCurrency")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateCurrency {

    @WebResult(name = "updateCurrencyResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateCurrency/UpdateCurrencyResponse/v1", partName = "response")
    @WebMethod(operationName = "UpdateCurrency", action = "http://www.sample.project.com.au/services/admin/UpdateCurrency/v1")
    public au.com.project.sample.services.admin.updatecurrency.UpdateCurrencyResponse updateCurrency(
        @WebParam(partName = "request", name = "updateCurrencyRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateCurrency/UpdateCurrencyRequest/v1")
        au.com.project.sample.services.admin.updatecurrency.UpdateCurrencyRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
