package au.com.project.sample.registration.services.savestate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-05T13:43:02.128+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/registration/services/SaveState/v1", name = "SaveState")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SaveState {

    @WebResult(name = "saveStateResponse", targetNamespace = "http://www.sample.project.com.au/registration/services/SaveState/SaveStateResponse/v1", partName = "response")
    @WebMethod(operationName = "SaveState", action = "http://www.sample.project.com.au/registration/services/SaveState/v1")
    public au.com.project.sample.registration.services.savestate.SaveStateResponse saveState(
        @WebParam(partName = "request", name = "saveStateRequest", targetNamespace = "http://www.sample.project.com.au/registration/services/SaveState/SaveStateRequest/v1")
        au.com.project.sample.registration.services.savestate.SaveStateRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
