package au.com.project.sample.services.admin.createrole;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-19T01:39:36.040+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/CreateRole/v1", name = "CreateRole")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateRole {

    @WebResult(name = "createRoleResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateRole/CreateRoleResponse/v1", partName = "response")
    @WebMethod(operationName = "CreateRole", action = "http://www.sample.project.com.au/services/admin/CreateRole/v1")
    public au.com.project.sample.services.admin.createrole.CreateRoleResponse createRole(
        @WebParam(partName = "request", name = "createRoleRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateRole/CreateRoleRequest/v1")
        au.com.project.sample.services.admin.createrole.CreateRoleRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
