package au.com.project.sample.registration.services.updatestate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-05T13:43:35.493+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/registration/services/UpdateState/v1", name = "UpdateState")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateState {

    @WebResult(name = "updateStateResponse", targetNamespace = "http://www.sample.project.com.au/registration/services/UpdateState/UpdateStateResponse/v1", partName = "response")
    @WebMethod(operationName = "UpdateState", action = "http://www.sample.project.com.au/registration/services/UpdateState/v1")
    public au.com.project.sample.registration.services.updatestate.UpdateStateResponse updateState(
        @WebParam(partName = "request", name = "updateStateRequest", targetNamespace = "http://www.sample.project.com.au/registration/services/UpdateState/UpdateStateRequest/v1")
        au.com.project.sample.registration.services.updatestate.UpdateStateRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
