package au.com.project.sample.services.admin.createsubcategory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-20T20:47:27.808+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/CreateSubCategory/v1", name = "CreateSubCategory")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateSubCategory {

    @WebResult(name = "createSubCategoryResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateSubCategory/CreateSubCategoryResponse/v1", partName = "response")
    @WebMethod(operationName = "CreateSubCategory", action = "http://www.sample.project.com.au/services/admin/CreateSubCategory/v1")
    public au.com.project.sample.services.admin.createsubcategory.CreateSubCategoryResponse createSubCategory(
        @WebParam(partName = "request", name = "createSubCategoryRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateSubCategory/CreateSubCategoryRequest/v1")
        au.com.project.sample.services.admin.createsubcategory.CreateSubCategoryRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
