package au.com.project.sample.services.admin.updatedesignation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2 2013-02-24T02:22:09.698+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateDesignation/v1", name = "UpdateDesignation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateDesignation {

	@WebResult(name = "updateDesignationResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateDesignation/UpdateDesignationResponse/v1", partName = "response")
	@WebMethod(operationName = "UpdateDesignation", action = "http://www.sample.project.com.au/services/admin/UpdateDesignation/v1")
	public au.com.project.sample.services.admin.updatedesignation.UpdateDesignationResponse updateDesignation(
			@WebParam(partName = "request", name = "updateDesignationRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateDesignation/UpdateDesignationRequest/v1") au.com.project.sample.services.admin.updatedesignation.UpdateDesignationRequest request)
			throws au.com.project.sample.common.message.TechnicalFault,
			au.com.project.sample.common.message.BusinessFault;
}
