package au.com.project.sample.services.admin.getcategory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:22.247+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/GetCategory/v1", name = "GetCategory")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetCategory {

    @WebResult(name = "getCategoryResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/GetCategory/GetCategoryResponse/v1", partName = "response")
    @WebMethod(operationName = "GetCategory", action = "http://www.sample.project.com.au/services/admin/GetCategory/v1")
    public au.com.project.sample.services.admin.getcategory.GetCategoryResponse getCategory(
        @WebParam(partName = "request", name = "getCategoryRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/GetCategory/GetCategoryRequest/v1")
        au.com.project.sample.services.admin.getcategory.GetCategoryRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
