package au.com.project.sample.services.account.createeducationsummary;

import org.springframework.beans.factory.annotation.Autowired;

import au.com.project.sample.process.EducationSummaryController;
import au.com.project.sample.process.impl.dto.UserInfoDTO;
import au.com.project.sample.services.account.createaccount.CreateEducationSummaryRequest;
import au.com.project.sample.services.account.createaccount.CreateEducationSummaryResponse;
import au.com.project.sample.services.model.UserInfo;

/**
 * This class was generated by Apache CXF 2.5.2 2013-02-21T21:05:01.353+11:00
 * Generated source version: 2.5.2
 * 
 */
public class CreateEducationSummaryManager {
	@Autowired
	EducationSummaryController educationSummaryController;

	private UserInfoDTO updateUserInfoDTO(
			CreateEducationSummaryRequest createEducationSummaryRequest) {
		UserInfoDTO userInfoDTO = new UserInfoDTO();

		UserInfo userInfo = createEducationSummaryRequest.getMessage()
				.getUserInfo();
		userInfoDTO.setFirstName(userInfo.getFirstName());
		userInfoDTO.setLastName(userInfo.getLastName());
		userInfoDTO.setConfirmPassword(userInfo.getConfirmPassword());
		userInfoDTO.setLastName(userInfo.getEmailId());
		userInfoDTO.setLocation(userInfo.getLocation());
		userInfoDTO.setPassword(userInfo.getPassword());
		userInfoDTO.setPhoneNumber(userInfo.getPhoneNumber());
		userInfoDTO.setUsername(userInfo.getUsername());
		userInfoDTO.setDateOfBirth(userInfo.getDateOfBirth());
		userInfoDTO.setGender(userInfo.getGender());

		return userInfoDTO;
	}

	public CreateEducationSummaryResponse createEducationSummaryResponse(
			CreateEducationSummaryRequest createEducationSummaryRequest) {
		CreateEducationSummaryResponse createEducationSummaryResponse = new CreateEducationSummaryResponse();

		createEducationSummaryResponse
				.setMessage(new CreateEducationSummaryResponse.Message());

		educationSummaryController
				.createEducationSummary(updateUserInfoDTO(createEducationSummaryRequest));

		createEducationSummaryResponse.getMessage().setStatus(true);

		return createEducationSummaryResponse;
	}

	public EducationSummaryController getEducationSummaryController() {
		return educationSummaryController;
	}

	public void setEducationSummaryController(
			EducationSummaryController educationSummaryController) {
		this.educationSummaryController = educationSummaryController;
	}

}
