package au.com.project.sample.services.account.createeducationsummary;

import org.springframework.beans.factory.annotation.Autowired;

import au.com.project.sample.process.EducationSummaryController;

/**
 * This class was generated by Apache CXF 2.5.2 2013-02-21T21:05:01.353+11:00
 * Generated source version: 2.5.2
 * 
 */
public class CreateEducationSummaryManager {
	@Autowired
	EducationSummaryController educationSummaryController;

	public EducationSummaryController getEducationSummaryController() {
		return educationSummaryController;
	}

	public void setEducationSummaryController(
			EducationSummaryController educationSummaryController) {
		this.educationSummaryController = educationSummaryController;
	}

}
