package au.com.project.sample.services.admin.deletestate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:14.403+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteState/v1", name = "DeleteState")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteState {

    @WebResult(name = "deleteStateResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteState/DeleteStateResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteState", action = "http://www.sample.project.com.au/services/admin/DeleteState/v1")
    public au.com.project.sample.services.admin.deletestate.DeleteStateResponse deleteState(
        @WebParam(partName = "request", name = "deleteStateRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteState/DeleteStateRequest/v1")
        au.com.project.sample.services.admin.deletestate.DeleteStateRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
