package au.com.project.sample.registration.services.setcity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-05T13:43:07.120+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/registration/services/SetCity/v1", name = "SetCity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SetCity {

    @WebResult(name = "setCityResponse", targetNamespace = "http://www.sample.project.com.au/registration/services/SetCity/SetCityResponse/v1", partName = "response")
    @WebMethod(operationName = "SetCity", action = "http://www.sample.project.com.au/registration/services/SetCity/v1")
    public au.com.project.sample.registration.services.setcity.SetCityResponse setCity(
        @WebParam(partName = "request", name = "setCityRequest", targetNamespace = "http://www.sample.project.com.au/registration/services/SetCity/SetCityRequest/v1")
        au.com.project.sample.registration.services.setcity.SetCityRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
