package au.com.project.sample.services.admin.getcurrency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:34.066+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/GetCurrency/v1", name = "GetCurrency")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetCurrency {

    @WebResult(name = "getCurrencyResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/GetCurrency/GetCurrencyResponse/v1", partName = "response")
    @WebMethod(operationName = "GetCurrency", action = "http://www.sample.project.com.au/services/admin/GetCurrency/v1")
    public au.com.project.sample.services.admin.getcurrency.GetCurrencyResponse getCurrency(
        @WebParam(partName = "request", name = "getCurrencyRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/GetCurrency/GetCurrencyRequest/v1")
        au.com.project.sample.services.admin.getcurrency.GetCurrencyRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
