package au.com.project.sample.services.admin.getcity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:26.268+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/GetCity/v1", name = "GetCity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetCity {

    @WebResult(name = "getCityResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/GetCity/GetCityResponse/v1", partName = "response")
    @WebMethod(operationName = "GetCity", action = "http://www.sample.project.com.au/services/admin/GetCity/v1")
    public au.com.project.sample.services.admin.getcity.GetCityResponse getCity(
        @WebParam(partName = "request", name = "getCityRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/GetCity/GetCityRequest/v1")
        au.com.project.sample.services.admin.getcity.GetCityRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
