package au.com.project.sample.services.admin.updatesubcategory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:22:39.047+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateSubCategory/v1", name = "UpdateSubCategory")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateSubCategory {

    @WebResult(name = "updateSubCategoryResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateSubCategory/UpdateSubCategoryResponse/v1", partName = "response")
    @WebMethod(operationName = "UpdateSubCategory", action = "http://www.sample.project.com.au/services/admin/UpdateSubCategory/v1")
    public au.com.project.sample.services.admin.updatesubcategory.UpdateSubCategoryResponse updateSubCategory(
        @WebParam(partName = "request", name = "updateSubCategoryRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateSubCategory/UpdateSubCategoryRequest/v1")
        au.com.project.sample.services.admin.updatesubcategory.UpdateSubCategoryRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
