package au.com.project.sample.services.account.updateitskill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-23T17:48:19.287+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/account/UpdateITSkill/v1", name = "UpdateITSkill")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateITSkill {

    @WebResult(name = "updateITSkillResponse", targetNamespace = "http://www.sample.project.com.au/services/account/UpdateITSkill/UpdateITSkillResponse/v1", partName = "response")
    @WebMethod(operationName = "UpdateITSkill", action = "http://www.sample.project.com.au/services/account/UpdateITSkill/v1")
    public au.com.project.sample.services.account.updateitskill.UpdateITSkillResponse updateITSkill(
        @WebParam(partName = "request", name = "updateITSkillRequest", targetNamespace = "http://www.sample.project.com.au/services/account/UpdateITSkill/UpdateITSkillRequest/v1")
        au.com.project.sample.services.account.updateitskill.UpdateITSkillRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
