package au.com.project.sample.services.admin.getsubcategory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:49.971+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/GetSubCategory/v1", name = "GetSubCategory")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetSubCategory {

    @WebResult(name = "getSubCategoryResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/GetSubCategory/GetSubCategoryResponse/v1", partName = "response")
    @WebMethod(operationName = "GetSubCategory", action = "http://www.sample.project.com.au/services/admin/GetSubCategory/v1")
    public au.com.project.sample.services.admin.getsubcategory.GetSubCategoryResponse getSubCategory(
        @WebParam(partName = "request", name = "getSubCategoryRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/GetSubCategory/GetSubCategoryRequest/v1")
        au.com.project.sample.services.admin.getsubcategory.GetSubCategoryRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
