<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.sample.project.com.au/services/admin/DeleteCity/v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:pref="http://www.sample.project.com.au/services/admin/DeleteCity/DeleteCityRequest/v1"
	xmlns:pref1="http://www.sample.project.com.au/services/admin/DeleteCity/DeleteCityResponse/v1"
	name="DeleteCity"
	targetNamespace="http://www.sample.project.com.au/services/admin/DeleteCity/v1"
	xmlns:fault="http://www.sample.project.com.au/common/message/FaultMessage/v1">
	<wsdl:import location="../../../../common/messages/1.0/FaultMessage.wsdl"
		namespace="http://www.sample.project.com.au/common/message/FaultMessage/v1"></wsdl:import>
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.sample.project.com.au/services/admin/DeleteCity/v1"
			xmlns:pref="http://www.sample.project.com.au/services/admin/DeleteCity/DeleteCityRequest/v1"
			xmlns:pref1="http://www.sample.project.com.au/services/admin/DeleteCity/DeleteCityResponse/v1"
			xmlns:pref2="http://www.sample.project.com.au/common/message/TechnicalException/v1">
			<xsd:import schemaLocation="DeleteCityRequest.xsd"
				namespace="http://www.sample.project.com.au/services/admin/DeleteCity/DeleteCityRequest/v1">
			</xsd:import>
			<xsd:import schemaLocation="DeleteCityResponse.xsd"
				namespace="http://www.sample.project.com.au/services/admin/DeleteCity/DeleteCityResponse/v1">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="deleteCityRequest">
		<wsdl:part element="pref:deleteCityRequest" name="request" />
	</wsdl:message>
	<wsdl:message name="deleteCityResponse">
		<wsdl:part element="pref1:deleteCityResponse" name="response" />
	</wsdl:message>
	<wsdl:portType name="DeleteCity">
		<wsdl:operation name="DeleteCity">
			<wsdl:input message="tns:deleteCityRequest" />
			<wsdl:output message="tns:deleteCityResponse" />
			<wsdl:fault name="technicalFault" message="fault:technicalFault" />
			<wsdl:fault name="businessFault" message="fault:businessFault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="DeleteCitySOAP" type="tns:DeleteCity">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="DeleteCity">
			<soap:operation
				soapAction="http://www.sample.project.com.au/services/admin/DeleteCity/v1" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="DeleteCity">
		<wsdl:port binding="tns:DeleteCitySOAP" name="DeleteCitySOAP">
			<soap:address location="http://localhost/service/-1.0" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
