package au.com.project.sample.services.account.deleteitskill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-23T17:48:14.489+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/account/DeleteITSkill/v1", name = "DeleteITSkill")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteITSkill {

    @WebResult(name = "deleteITSkillResponse", targetNamespace = "http://www.sample.project.com.au/services/account/DeleteITSkill/DeleteITSkillResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteITSkill", action = "http://www.sample.project.com.au/services/account/DeleteITSkill/v1")
    public au.com.project.sample.services.account.deleteitskill.DeleteITSkillResponse deleteITSkill(
        @WebParam(partName = "request", name = "deleteITSkillRequest", targetNamespace = "http://www.sample.project.com.au/services/account/DeleteITSkill/DeleteITSkillRequest/v1")
        au.com.project.sample.services.account.deleteitskill.DeleteITSkillRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
