package au.com.project.sample.services.account.createitskill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-23T17:48:09.553+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/account/CreateITSkill/v1", name = "CreateITSkill")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateITSkill {

    @WebResult(name = "createITSkillResponse", targetNamespace = "http://www.sample.project.com.au/services/account/CreateITSkill/CreateITSkillResponse/v1", partName = "response")
    @WebMethod(operationName = "CreateITSkill", action = "http://www.sample.project.com.au/services/account/CreateITSkill/v1")
    public au.com.project.sample.services.account.createitskill.CreateITSkillResponse createITSkill(
        @WebParam(partName = "request", name = "createITSkillRequest", targetNamespace = "http://www.sample.project.com.au/services/account/CreateITSkill/CreateITSkillRequest/v1")
        au.com.project.sample.services.account.createitskill.CreateITSkillRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
