package au.com.project.sample.services.admin.getdesignation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:38.065+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/GetDesignation/v1", name = "GetDesignation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetDesignation {

    @WebResult(name = "getDesignationResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/GetDesignation/GetDesignationResponse/v1", partName = "response")
    @WebMethod(operationName = "GetDesignation", action = "http://www.sample.project.com.au/services/admin/GetDesignation/v1")
    public au.com.project.sample.services.admin.getdesignation.GetDesignationResponse getDesignation(
        @WebParam(partName = "request", name = "getDesignationRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/GetDesignation/GetDesignationRequest/v1")
        au.com.project.sample.services.admin.getdesignation.GetDesignationRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
