package au.com.project.sample.services.admin.deletesubcategory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:18.271+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteSubCategory/v1", name = "DeleteSubCategory")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteSubCategory {

    @WebResult(name = "deleteSubCategoryResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteSubCategory/DeleteSubCategoryResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteSubCategory", action = "http://www.sample.project.com.au/services/admin/DeleteSubCategory/v1")
    public au.com.project.sample.services.admin.deletesubcategory.DeleteSubCategoryResponse deleteSubCategory(
        @WebParam(partName = "request", name = "deleteSubCategoryRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteSubCategory/DeleteSubCategoryRequest/v1")
        au.com.project.sample.services.admin.deletesubcategory.DeleteSubCategoryRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
