<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.sample.project.com.au/services/admin/CreateCity/v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:pref="http://www.sample.project.com.au/services/admin/CreateCity/CreateCityRequest/v1"
	xmlns:pref1="http://www.sample.project.com.au/services/admin/CreateCity/CreateCityResponse/v1"
	name="CreateCity"
	targetNamespace="http://www.sample.project.com.au/services/admin/CreateCity/v1"
	xmlns:fault="http://www.sample.project.com.au/common/message/FaultMessage/v1">
	<wsdl:import location="../../../../common/messages/1.0/FaultMessage.wsdl"
		namespace="http://www.sample.project.com.au/common/message/FaultMessage/v1"></wsdl:import>
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.sample.project.com.au/services/admin/CreateCity/v1"
			xmlns:pref="http://www.sample.project.com.au/services/admin/CreateCity/CreateCityRequest/v1"
			xmlns:pref1="http://www.sample.project.com.au/services/admin/CreateCity/CreateCityResponse/v1"
			xmlns:pref2="http://www.sample.project.com.au/common/message/TechnicalException/v1">
			<xsd:import schemaLocation="CreateCityRequest.xsd"
				namespace="http://www.sample.project.com.au/services/admin/CreateCity/CreateCityRequest/v1">
			</xsd:import>
			<xsd:import schemaLocation="CreateCityResponse.xsd"
				namespace="http://www.sample.project.com.au/services/admin/CreateCity/CreateCityResponse/v1">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="createCityRequest">
		<wsdl:part element="pref:createCityRequest" name="request" />
	</wsdl:message>
	<wsdl:message name="createCityResponse">
		<wsdl:part element="pref1:createCityResponse" name="response" />
	</wsdl:message>
	<wsdl:portType name="CreateCity">
		<wsdl:operation name="CreateCity">
			<wsdl:input message="tns:createCityRequest" />
			<wsdl:output message="tns:createCityResponse" />
			<wsdl:fault name="technicalFault" message="fault:technicalFault" />
			<wsdl:fault name="businessFault" message="fault:businessFault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CreateCitySOAP" type="tns:CreateCity">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="CreateCity">
			<soap:operation
				soapAction="http://www.sample.project.com.au/services/admin/CreateCity/v1" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CreateCity">
		<wsdl:port binding="tns:CreateCitySOAP" name="CreateCitySOAP">
			<soap:address location="http://localhost/service/-1.0" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
