package au.com.project.sample.services.admin.createdesignation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-20T20:47:39.840+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/CreateDesignation/v1", name = "CreateDesignation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateDesignation {

    @WebResult(name = "createDesignationResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateDesignation/CreateDesignationResponse/v1", partName = "response")
    @WebMethod(operationName = "CreateDesignation", action = "http://www.sample.project.com.au/services/admin/CreateDesignation/v1")
    public au.com.project.sample.services.admin.createdesignation.CreateDesignationResponse createDesignation(
        @WebParam(partName = "request", name = "createDesignationRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/CreateDesignation/CreateDesignationRequest/v1")
        au.com.project.sample.services.admin.createdesignation.CreateDesignationRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
