package au.com.project.sample.registration.services.setcountry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-05T13:43:12.231+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/registration/services/SetCountry/v1", name = "SetCountry")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SetCountry {

    @WebResult(name = "setCountryResponse", targetNamespace = "http://www.sample.project.com.au/registration/services/SetCountry/v1", partName = "response")
    @WebMethod(operationName = "SetCountry", action = "http://www.sample.project.com.au/registration/services/SetCountry/v1")
    public au.com.project.sample.registration.services.setcountry.SetCountryResponse setCountry(
        @WebParam(partName = "request", name = "setCountryRequest", targetNamespace = "http://www.sample.project.com.au/registration/services/SetCountry/v1")
        au.com.project.sample.registration.services.setcountry.SetCountryRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
