
package au.com.project.sample.common.message;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-14T19:46:10.245+11:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "technicalException", targetNamespace = "http://www.sample.project.com.au/common/message/TechnicalException/v1")
public class TechnicalFault extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private au.com.project.sample.common.message.TechnicalException technicalException;

    public TechnicalFault() {
        super();
    }
    
    public TechnicalFault(String message) {
        super(message);
    }
    
    public TechnicalFault(String message, Throwable cause) {
        super(message, cause);
    }

    public TechnicalFault(String message, au.com.project.sample.common.message.TechnicalException technicalException) {
        super(message);
        this.technicalException = technicalException;
    }

    public TechnicalFault(String message, au.com.project.sample.common.message.TechnicalException technicalException, Throwable cause) {
        super(message, cause);
        this.technicalException = technicalException;
    }

    public au.com.project.sample.common.message.TechnicalException getFaultInfo() {
        return this.technicalException;
    }
}
