<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.sample.project.com.au/registration/services/GetCity/v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:pref="http://www.sample.project.com.au/registration/services/GetCity/GetCityRequest/v1"
	xmlns:pref1="http://www.sample.project.com.au/registration/services/GetCity/GetCityResponse/v1"
	name="GetCity"
	targetNamespace="http://www.sample.project.com.au/registration/services/GetCity/v1"
	xmlns:fault="http://www.sample.project.com.au/common/message/FaultMessage/v1">
	<wsdl:import location="../../../../common/messages/1.0/FaultMessage.wsdl"
		namespace="http://www.sample.project.com.au/common/message/FaultMessage/v1"></wsdl:import>
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.sample.project.com.au/registration/services/GetCity/v1"
			xmlns:pref="http://www.sample.project.com.au/registration/services/GetCity/GetCityRequest/v1"
			xmlns:pref1="http://www.sample.project.com.au/registration/services/GetCity/GetCityResponse/v1"
			xmlns:pref2="http://www.sample.project.com.au/common/message/TechnicalException/v1">
			<xsd:import schemaLocation="GetCityRequest.xsd"
				namespace="http://www.sample.project.com.au/registration/services/GetCity/GetCityRequest/v1">
			</xsd:import>
			<xsd:import schemaLocation="GetCityResponse.xsd"
				namespace="http://www.sample.project.com.au/registration/services/GetCity/GetCityResponse/v1">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="getCityRequest">
		<wsdl:part element="pref:getCityRequest" name="request" />
	</wsdl:message>
	<wsdl:message name="getCityResponse">
		<wsdl:part element="pref1:getCityResponse" name="response" />
	</wsdl:message>
	<wsdl:portType name="GetCity">
		<wsdl:operation name="GetCity">
			<wsdl:input message="tns:getCityRequest" />
			<wsdl:output message="tns:getCityResponse" />
			<wsdl:fault name="technicalFault" message="fault:technicalFault" />
			<wsdl:fault name="businessFault" message="fault:businessFault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetCitySOAP" type="tns:GetCity">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="GetCity">
			<soap:operation
				soapAction="http://www.sample.project.com.au/registration/services/GetCity/v1" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetCity">
		<wsdl:port binding="tns:GetCitySOAP" name="GetCitySOAP">
			<soap:address location="http://localhost/service/-1.0" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
