package au.com.project.sample.registration.services.deletestate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-05T13:42:31.690+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/registration/services/DeleteState/v1", name = "DeleteState")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteState {

    @WebResult(name = "deleteStateResponse", targetNamespace = "http://www.sample.project.com.au/registration/services/DeleteState/DeleteStateResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteState", action = "http://www.sample.project.com.au/registration/services/DeleteState/v1")
    public au.com.project.sample.registration.services.deletestate.DeleteStateResponse deleteState(
        @WebParam(partName = "request", name = "deleteStateRequest", targetNamespace = "http://www.sample.project.com.au/registration/services/DeleteState/DeleteStateRequest/v1")
        au.com.project.sample.registration.services.deletestate.DeleteStateRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
