package au.com.project.sample.services.admin.updatecity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:58.005+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateCity/v1", name = "UpdateCity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateCity {

    @WebResult(name = "updateCityResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateCity/UpdateCityResponse/v1", partName = "response")
    @WebMethod(operationName = "UpdateCity", action = "http://www.sample.project.com.au/services/admin/UpdateCity/v1")
    public au.com.project.sample.services.admin.updatecity.UpdateCityResponse updateCity(
        @WebParam(partName = "request", name = "updateCityRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/UpdateCity/UpdateCityRequest/v1")
        au.com.project.sample.services.admin.updatecity.UpdateCityRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
