package au.com.project.sample.services.account.updateemploymentsummary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-22T11:38:36.422+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/account/UpdateEmploymentSummary/v1", name = "UpdateEmploymentSummary")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateEmploymentSummary {

    @WebResult(name = "updateEmploymentSummaryResponse", targetNamespace = "http://www.sample.project.com.au/services/account/UpdateEmploymentSummary/UpdateEmploymentSummaryResponse/v1", partName = "response")
    @WebMethod(operationName = "UpdateEmploymentSummary", action = "http://www.sample.project.com.au/services/account/UpdateEmploymentSummary/v1")
    public au.com.project.sample.services.account.updateemploymentsummary.UpdateEmploymentSummaryResponse updateEmploymentSummary(
        @WebParam(partName = "request", name = "updateEmploymentSummaryRequest", targetNamespace = "http://www.sample.project.com.au/services/account/UpdateEmploymentSummary/UpdateEmploymentSummaryRequest/v1")
        au.com.project.sample.services.account.updateemploymentsummary.UpdateEmploymentSummaryRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
