package au.com.project.sample.services.account.createemploymentsummary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-21T21:05:20.482+11:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/account/CreateEmploymentSummary/v1", name = "CreateEmploymentSummary")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateEmploymentSummary {

    @WebResult(name = "createEmploymentSummaryResponse", targetNamespace = "http://www.sample.project.com.au/services/account/CreateEmploymentSummary/CreateEmploymentSummaryResponse/v1", partName = "response")
    @WebMethod(operationName = "CreateEmploymentSummary", action = "http://www.sample.project.com.au/services/account/CreateEmploymentSummary/v1")
    public au.com.project.sample.services.account.createemploymentsummary.CreateEmploymentSummaryResponse createEmploymentSummary(
        @WebParam(partName = "request", name = "createEmploymentSummaryRequest", targetNamespace = "http://www.sample.project.com.au/services/account/CreateEmploymentSummary/CreateEmploymentSummaryRequest/v1")
        au.com.project.sample.services.account.createemploymentsummary.CreateEmploymentSummaryRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
