package au.com.project.sample.services.admin.deletedesignation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:06.367+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteDesignation/v1", name = "DeleteDesignation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteDesignation {

    @WebResult(name = "deleteDesignationResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteDesignation/DeleteDesignationResponse/v1", partName = "response")
    @WebMethod(operationName = "DeleteDesignation", action = "http://www.sample.project.com.au/services/admin/DeleteDesignation/v1")
    public au.com.project.sample.services.admin.deletedesignation.DeleteDesignationResponse deleteDesignation(
        @WebParam(partName = "request", name = "deleteDesignationRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/DeleteDesignation/DeleteDesignationRequest/v1")
        au.com.project.sample.services.admin.deletedesignation.DeleteDesignationRequest request
    ) throws au.com.project.sample.common.message.TechnicalFault, au.com.project.sample.common.message.BusinessFault;
}
