<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.sample.project.com.au/registration/services/DeleteCountry/v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="DeleteCountry"
	targetNamespace="http://www.sample.project.com.au/registration/services/DeleteCountry/v1"
	xmlns:fault="http://www.sample.project.com.au/common/message/FaultMessage/v1">
	<wsdl:import location="../../../../common/messages/1.0/FaultMessage.wsdl"
		namespace="http://www.sample.project.com.au/common/message/FaultMessage/v1"></wsdl:import>
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.sample.project.com.au/registration/services/DeleteCountry/v1"
			xmlns:pref="http://www.sample.project.com.au/registration/services/DeleteCountry/DeleteCountryRequest/v1"
			xmlns:pref1="http://www.sample.project.com.au/registration/services/DeleteCountry/DeleteCountryResponse/v1"
			xmlns:pref2="http://www.sample.project.com.au/common/message/TechnicalException/v1">
			<xsd:import schemaLocation="DeleteCountryRequest.xsd"
				namespace="http://www.sample.project.com.au/registration/services/DeleteCountry/DeleteCountryRequest/v1">
			</xsd:import>
			<xsd:import schemaLocation="DeleteCountryResponse.xsd"
				namespace="http://www.sample.project.com.au/registration/services/DeleteCountry/DeleteCountryResponse/v1">
			</xsd:import>
			<xsd:element name="deleteCountryRequest" type="pref:DeleteCountryRequest"></xsd:element>
			<xsd:element name="deleteCountryResponse" type="pref1:DeleteCountryResponse"></xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="deleteCountryRequest">
		<wsdl:part element="tns:deleteCountryRequest" name="request" />
	</wsdl:message>
	<wsdl:message name="deleteCountryResponse">
		<wsdl:part element="tns:deleteCountryResponse" name="response" />
	</wsdl:message>
	<wsdl:portType name="DeleteCountry">
		<wsdl:operation name="DeleteCountry">
			<wsdl:input message="tns:deleteCountryRequest" />
			<wsdl:output message="tns:deleteCountryResponse" />
			<wsdl:fault name="technicalFault" message="fault:technicalFault" />
			<wsdl:fault name="businessFault" message="fault:businessFault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="DeleteCountrySOAP" type="tns:DeleteCountry">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="DeleteCountry">
			<soap:operation
				soapAction="http://www.sample.project.com.au/registration/services/DeleteCountry/v1" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="DeleteCountry">
		<wsdl:port binding="tns:DeleteCountrySOAP" name="DeleteCountrySOAP">
			<soap:address location="http://localhost/service/-1.0" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
