package au.com.project.sample.services.admin.getrole;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-02-24T02:21:41.982+11:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://www.sample.project.com.au/services/admin/GetRole/v1", name = "GetRole")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetRole {

    @WebResult(name = "getRoleResponse", targetNamespace = "http://www.sample.project.com.au/services/admin/GetRole/GetRoleResponse/v1", partName = "response")
    @WebMethod(operationName = "GetRole", action = "http://www.sample.project.com.au/services/admin/GetRole/v1")
    public au.com.project.sample.services.admin.getrole.GetRoleResponse getRole(
        @WebParam(partName = "request", name = "getRoleRequest", targetNamespace = "http://www.sample.project.com.au/services/admin/GetRole/GetRoleRequest/v1")
        au.com.project.sample.services.admin.getrole.GetRoleRequest request
    ) throws au.com.project.sample.common.message.BusinessFault, au.com.project.sample.common.message.TechnicalFault;
}
